# Generated by Django 5.2.6 on 2025-09-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('historic', 'Historic'), ('exclusive', 'Exclusive'), ('fan', 'Fan'), ('misc', 'Miscellanous')])),
                ('is_featured', models.BooleanField()),
            ],
        ),
    ]
