# Generated by Django 5.2.6 on 2025-09-15 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default='No description available')),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('historic', 'Historic'), ('exclusive', 'Exclusive'), ('fan', 'Fan'), ('misc', 'Miscellanous')], default='misc', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
